### ISSUE TITLE
Warning `imp` module is deprecated

### ISSUE THREAD

**Issue by acabarbaye** [mhammond/pywin32#1503] opened 2020-04-23 09:07 UTC
When using pywin32 on Python3, I get the following warning:
```
##[warning]the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
There are few places in the code where the `imp` module is imported e.g. https://github.com/mhammond/pywin32/blob/d64fac8d7bda2cb1d81e2c9366daf99e802e327f/win32/Lib/pywintypes.py#L2.

**Comment by knudsvik** [comment] 2020-06-13 11:11
Should be closed as it is covered by #1256

**Comment by mhammond** [comment] 2020-06-13 12:38
Thanks, it is a dupe of #1256

**Comment by mhammond** [comment] 2020-06-22 07:26
I backed this out as it broke Python 2. I'm in the process of "formally" killing support for python 2, so I'll reapply it after that.

**Comment by mhammond** [comment] 2020-06-22 07:27
Actually, it may not be just python 3 - see the failed jobs on master.

**Closed** 2020-10-24 05:36 UTC
