### ISSUE TITLE
No source tar on pypi for pywin32

### ISSUE THREAD

**Issue by agusdb** [mhammond/pywin32#1368] opened 2019-07-12 21:57 UTC
https://pypi.org/project/pypiwin32/ provided a source .tar.gz release for each version, but https://pypi.org/project/pywin32/ does not.

**Comment by Avasam** [comment] 2024-07-28 02:14
Duplicate of https://github.com/mhammond/pywin32/issues/1857
A source distribution would require you to build it on download/install, and it's highly likely that you won't have all the right build tools and compilers installed.

You wouldn't gain much, if anything, from a source distribution anyway, as it's not like you could build it for a specific OS (Windows only) or a new Python version (nearly every major Python version has had breaking changes affecting pywin32).

What's your use-case? If you really want to build from source, you can build from the GitHub source or clone the source yourself.

**Closed by Avasam** 2024-07-28 02:14 UTC
