### ISSUE TITLE
Python3.7 only supports pywin32 (223). Any higher version will produce `DLL load failed: The specified procedure could not be found`

### ISSUE THREAD

**Issue by Coderx7** [mhammond/pywin32#1507] opened 2020-04-28 06:40 UTC
I noticed any versions higher than 223 wont work with Python3.7.4 and will generate :
```python
ImportError: DLL load failed: The specified procedure could not be found.
```
I tested different approaches and yes I do run the `pywin32_postinstall.py -install` for all versions. 
There is also something weird and that is, intrestingly, importing modules in `PythonWin` doesnt issue any errors at all while basically everywhere else the error exists and turns up!  

* Expected behavior: Newer versions should also work well on Python3.7.4   
* Atual behavior: Only version `223 `works with Python 3.7.4  
* Steps to reproduce the problem : 
  1. Install the Python3.7.4, 
  2. Install Pywin32 the latest version (either using the installer or pip)
  3. Import win32api

* Version of Python and pywin32
Python: 
```
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
```
pywin32 : all versions greater than 223 wont work 
```
224, 225, 226, 227
```

**Comment by mhammond** [comment] 2020-04-28 06:46
Anaconda's Python packages parts of an old pywin32. See #1409, #1406, #1180, etc - I really should clean these up and dupe some against each other, but I think #1409 has the clearest description. I'm going to close this as I don't think it adds anything new to those issues, but I'm happy to reopen if that's wrong.

**Closed by mhammond** 2020-04-28 06:46 UTC

**Comment by Coderx7** [comment] 2020-04-28 07:36
Thanks a lot really apprecaite it. managed to solved it based on this [comment ](https://github.com/mhammond/pywin32/issues/1406#issuecomment-549223379) .
Basically this as you said was caused becasue of the "Older" dlls still be reciding some where and thus not allowing for the newer dlls to replace them. 
What I actually did was to uninstall the old version (my current version) then Installed [Everything](https://www.voidtools.com/downloads/) and searched for these two DLLs : ( `pythoncom37.dll` and `pywintypes37.dll`) and lo and behold! there were dozens of them scattered in different anaconda3's directories and also in system32.  
I deleted all of them. (Important note, I also had to close any open editor, in my case my VSCode)  and then simply did : 
```
pip install pywin32
```
followed by 
```
python \Scripts\pywin32_postinstall.py -install
``` 
and thats it. all is fine now and the DLL issue is gone for good!
Thank you very much for your prompt reply and help.
Have a wonderful day sir ;)

**Comment by johann-petrak** [comment] 2021-01-30 21:26
I just got this bug after installing miniconda and python 3.9 in a separate environment and subsequently other packages using pip.

I never installed pywin32 explicitly. 

Then Jupyter notebook did not work and I found this jupyter issue: https://github.com/jupyter/notebook/issues/4980

Running python [environment path]/Scripts/pywin32_postinstall.py -install fixed this, but how on earth is this supposed to be something a user needs to do and figure out?

**Comment by mhammond** [comment] 2021-01-31 00:10
The problem is that jupyter bundles them in non-standard places. There's really no way pywin32 can know about that. You should file a bug asking them to install it via pip, or otherwise installed somewhere that a user trying to upgrade via pip succeeds.

**Comment by johann-petrak** [comment] 2021-01-31 07:50
Thanks, I was trying to figure out whose bug this is!

**Comment by johann-petrak** [comment] 2021-05-05 07:38
So it seems ultimately this should get dealt with by Anaconda see https://github.com/conda-forge/pywin32-feedstock/issues/18
