### ISSUE TITLE
win32com is mishandling in/out byref arguments

### ISSUE THREAD

**Issue by russleikis** [mhammond/pywin32#1303] opened 2019-01-25 17:37 UTC
I have an enterprise level customer who is trying to use one of our mature MFC application's COM interface via Python.  The customer is reporting issues with this, and as I explored it we found that the reported behavior is occurring due to the behavior in the Python win32com library.  Our application interface has some methods that do not work, but only when using Python.  Using .NET, VBA, Matlab, or LabVIEW, all methods work as expected in the same build.  I've reproduced the issues using the latest version of Anaconda, freshly downloaded and reinstalled.  My customer is using a Jupyter Notebook environment.

I have reproduced the issues outside of our product and have provided this project.

Note, I am a relative novice at Python and its entire ecosystem.  I believe this is the correct place for this bug report.  If not, I would appreciate the insight of where to go next.

Anaconda 2018.12 / Spyder 3.3.2 
Python 3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]

* Attachments
  * A zip archive ( [python_win32com_issue1303.zip](https://github.com/mhammond/pywin32/files/2797152/python_win32com_issue1303.zip) ) with the following: 
  * A VS2017 solution which provides a C++/MFC COM server app.  The executable and tlb are also provided if they cannot be built.  The executable must be run once to register the server.
  * A Python script which executes the provided COM methods and demonstrates two odd behaviors of win32com.
  * An Excel VBA example which executes the provided COM methods and demonstrates that they work successfully in other languages.

* Expected behavior and actual behavior.
The affected methods always have byref variant arguments.
  * Given a method signature of (VTS_I2, VTS_I2, VTS_PR4, VTS_PR4, VTS_PBOOL), the first two are input arguments and the next three are input/output arguments.  The result is that only the first in/out byref argument is populated by win32com, and any following arguments are modified from the initialization value, but are returned as zero, regardless of variant type.
Expected Behavior:
left bound: 1234.789
right bound: 6789.123
enabled: True
Actual behavior:
left bound: 1234.7889404296875
right bound: 0
enabled: 0

  * Given a method signature of (VTS_PR4, VTS_PR4, VTS_PBOOL), all arguments are populated, but in reverse order, regardless of variant type! This is the same as reported in bug https://github.com/mhammond/pywin32/issues/622.
Expected Behavior:
left bound: 1234.789
right bound: 6789.123
enabled: True
Actual behavior:
left bound: True
right bound: 6789.123046875
enabled: 1234.7889404296875

  * Given a method signature of (VTS_PR4) or (VTS_PBOOL) alone, these work correctly.
Single Float argument:
left bound: 1234.7889404296875
Single Boolean argument:
enabled: True

* Steps to reproduce the problem.
  * I have attached a Python script which produces these issues, a COM server to provide the interface, and an Excel (VBA) example to illustrate the problem is limited to Python win32com.

*edit* a grammar correction

**Comment by russleikis** [comment] 2019-02-14 00:03
I'm hoping to at least get an acknowledgment that this has been reviewed, but I'm new to Github.  Is that practiced here?

**Comment by mhammond** [comment] 2019-02-18 22:52
I can acknowledge I've seen it :) It may be some time before I get to look in detail, but you seem to be saying com argument handling is broken in a fundamental way, which I'd expect to have been noticed over the last 10 years (although I concede it's possible, and I may also be reading the report incorrectly) In the meantime, it would be great if you could look at the com/TestSources/PyCOMTest directory to see if you can make your test-cases fit in there.

**Comment by mhammond** [comment] 2019-02-18 23:02
And I neglected to thank you for the patch :( Thank you!

**Comment by russleikis** [comment] 2019-02-19 15:58
OK, great!  Thanks for letting me know.  I agree it looks like it is something fundamental and was surprising to my customer and I.  This may just be a irregular case.

I'll look at PyCOMTest soon.

**Comment by lokesh1990** [comment] 2019-05-08 19:28
Hi,
Any updates on this?

I kind of have the following issue:

I have a C# COM method as below:

> public void getTestData2(string[] test1)

I used pywin to test the above method and in the COM browser I see the following:

![image](https://user-images.githubusercontent.com/1056190/57401219-2a03a280-71a3-11e9-8165-a6911ba0e97c.png)

Now, I create the object and call it as follows

![image](https://user-images.githubusercontent.com/1056190/57401557-eb221c80-71a3-11e9-9a06-13ee78d34f3b.png)

and the corresponding line in that file is the return statement below:

> def getTestData2(self, test1=defaultNamedNotOptArg):
> 		return self._oleobj_.InvokeTypes(1610743933, LCID, 1, (24, 0), ((8200, 1),),test1
> 			)

I also tried this with not luck:

![image](https://user-images.githubusercontent.com/1056190/57402293-fcb7f400-71a4-11e9-9eb7-b81e6886dc77.png)

Obviously, I am a noob in python. Does anyone see what could be wrong? 

Thanks.

**Comment by rleikis** [comment] 2019-05-08 21:00
@lokesh1990 Hi, no updates from me.  I've not had any time to go back to this.  I have customers that do wish to be using python with our products but I have a steady stream of other customer issues and R&D projects on top of it all.  I keep the ticket open hoping to get back to it, but learning what I would need to to get into the PyCOMTest library isn't a high priority for my company when we didn't plan on supporting the language.

For your issue, it seems like it is not your SafeArray String argument but one of the arguments of InvokeTypes that is throwing the TypeError.  Based on the method definition I would expect that this would work.  I am unsure.

**Comment by lokesh1990** [comment] 2019-05-09 15:28
Hi,
I tried this again today and it worked with the following. I have no clue why.

```
a = ['']
newObj.getTestData2(a)
```

Sorry for the trouble. 
Thanks again.

**Comment by rleikis** [comment] 2019-08-01 18:11
@mhammond Hello Mark.  The affected customer has come back and still requires a fix for this issue, but I am unable to help him as the issue does not seem to be in our code.

I do not use Python often enough to consider myself proficient enough to do what you have asked.  I am only using Python in an Anaconda/Spyder environment and my time to learn your codebase and how to use your tests is very limited.

Is there any way you can take some time to pursue this, at least trying the examples we've already provided?  Even if you can identify a workaround that will play nicely with your library it would be a great step forward.

**Comment by thopiekar** [comment] 2019-08-01 19:11
@rleikis: Hey! Have you also tried to send this issue to the python-win32 mailing-list? I'm principally against any kind of spamming (asking questions at multiple locations), but @mhammond is recently busy. Therefore, I would suggest asking there for some further help.
I don't have many experiences around PyWin32, but I know that there are some people around there, who spent more time with it - for example T. Roberts. Maybe he knows about a workaround.
As far as I remember I faced the issue in the Autodesk Inventor plugin for Cura I wrote, but was able to use an alternative function in their API which allowed to set my values.

**Comment by rleikis** [comment] 2019-08-01 22:48
@thopiekar Thanks for the quick reply.  I did not know about the mailing list.  I will try there.

**Comment by thopiekar** [comment] 2019-08-02 07:32
No problem. The problem is confirmed by @mhammond , but with some luck there is an alternative way for you (and your client), too, to get your application working.

**Comment by mhammond** [comment] 2019-08-02 07:42
I haven't really confirmed the problem - this stuff is complex and subtle, and how optional args are handled isn't well specified by COM, and there are a few options (eg, arg count omitting them, a special variant type, etc). However, the varargs support in pywin32 does have reasonable tests, which is why I suggested looking at the test suite - it will at least demonstrate what pywin32 is doing. pywin32 does have *some* support for changing this behaviour - there's a special `pythoncom.Missing`, `.Empty` and `.ArgNotFound` which can be specified. However, I suspect I'm not going to find the time to dig into 3rd party c++ sources to figure out your problem.

**Comment by rleikis** [comment] 2019-08-02 20:13
Thanks.  I would like to point out that this doesn't involve optional parameters, but method signatures with a single versus multiple in/out byref arugments.  A single in/out byref argument works great, but more than one in a method signature and things get jumbled up.  Due to this I'm not certain the ideas presented are potential solutions.

Right now the only way I know of to support Python users is to rewrite the API to avoid more than one in/out byref argument in a single method signature.  This would not only break interface for all of our existing customers on a production API,  but also be laborious for users of the API to consume.

If I am mistaken please let me know.

**Comment by mhammond** [comment] 2019-08-05 07:59
Sorry, I misunderstood. Sadly https://github.com/mhammond/pywin32/blob/master/com/TestSources/PyCOMTest/PyCOMTest.idl doesn't seem to have multiple in/out args - there are a couple with multiple out args. I'll try and dig a little further, but it's not likely to happen soon I'm afraid.

**Comment by hauptmech** [comment] 2019-09-22 08:52
I'm facing this issue too. Here's an example signature from solidworks.

```
[id(0x00000005), helpstring("Gets data from matrix"), helpcontext(0x06900005)] 
		HRESULT GetData(
			[in, out] IDispatch** XAxisObjOut,
			[in, out] IDispatch** YAxisObjOut,
			[in, out] IDispatch** ZAxisObjOut,
			[in, out] IDispatch** TransformObjOut,
			[in, out] double* ScaleOut
		);
```

**Comment by mhammond** [comment] 2019-09-23 00:00
> Here's an example signature from solidworks.

What problem is this causing? What's the makepy generated output, or if you aren't using that, how are you trying to call it?

**Comment by hauptmech** [comment] 2019-09-23 00:34
byref arguments are populated in reverse order. Perhaps this should go in #622 instead?

relevant snippets from makepy, using GetData2 which has the exact same signature :
```
class IMathTransform(DispatchBaseClass):
	'Interface for MathTransform'
	CLSID = IID('{F7D97F82-162E-11D4-AEAB-00C04FA0AC51}')
	coclass_clsid = IID('{F7D97F83-162E-11D4-AEAB-00C04FA0AC51}')

	def GetData2(self, XAxisObjOut=defaultNamedNotOptArg, YAxisObjOut=defaultNamedNotOptArg, ZAxisObjOut=defaultNamedNotOptArg, TransformObjOut=defaultNamedNotOptArg
			, ScaleOut=defaultNamedNotOptArg):
		'Gets data from matrix'
		return self._ApplyTypes_(11, 1, (24, 0), ((16393, 3), (16393, 3), (16393, 3), (16393, 3), (16389, 3)), 'GetData2', None,XAxisObjOut

<snip>
IMathTransform_vtables_ = [
	(( 'GetData2' , 'XAxisObjOut' , 'YAxisObjOut' , 'ZAxisObjOut' , 'TransformObjOut' , 
			 'ScaleOut' , ), 11, (11, (), [ (16393, 3, None, None) , (16393, 3, None, None) , (16393, 3, None, None) , 
			 (16393, 3, None, None) , (16389, 3, None, None) , ], 1 , 1 , 4 , 0 , 152 , (3, 0, None, None) , 0 , )),

**Comment by qfdragon** [comment] 2020-09-27 15:18
Hi guys, do you have new information of this topic? I get this reversed out byref arguments when I call SolidWorks APIs, and I check the function `PyObject *PyIDispatch::InvokeTypes(PyObject *self, PyObject *args)` in the file "PyIDispatch.cpp", the reversed outing argument is here?
`dispparams.cArgs = numArgArray;
    if (dispparams.cArgs) {
        dispparams.rgvarg = new VARIANTARG[dispparams.cArgs];
        if (dispparams.rgvarg == NULL) {
            PyErr_SetString(PyExc_MemoryError, "Allocating dispparams.rgvarg array");
            goto error;
        }

        for (i = dispparams.cArgs; i--;) VariantInit(&dispparams.rgvarg[i]);

        for (i = 0; i < dispparams.cArgs; ++i) {
            // args in reverse order.
            // arg-helpers in normal order.
            UINT offset = dispparams.cArgs - i - 1;
            // See if the user actually specified this arg.
            PyObject *arg = i >= (UINT)numArgs ? Py_None : PyTuple_GET_ITEM(args, i + 5);
            if (!ArgHelpers[i].MakeObjToVariant(arg, &dispparams.rgvarg[offset],
                                                PyTuple_GET_ITEM(argsElemDescArray, i)))
                goto error;
        }
    }`

**Comment by rleikis** [comment] 2020-09-30 15:54
Sorry, no update here.  It remains a problem for our customers wanting to use Python.  I'm constrained with other projects at work, so I've not had the time to dig into it this source and find the problem.  Still, I'd be concerned about a fix breaking the library in a different way for existing users.  I'm not confident that I have a strong enough COM background to do it right, if it is even caused by some quirky COM thing, so I really think we need Mark to look at this to resolve.

**Comment by mhammond** [comment] 2020-09-30 22:31
I probably need a repro to make any progress here, and sadly, commercial closed source tools like solidworks doesn't really qualify. The best bet would be reproducing in the test objects in pywin32.

**Comment by rleikis** [comment] 2020-09-30 22:38
Sorry I'm not really familiar with how to unit test your project, but a kind reminder.  I originally provided a generic COM/server app and source code specifically to reproduce the case without requiring access to 3rd party commercial software.  This can be built and run using the free Visual Studio Community.

> A zip archive ( python_win32com_issue1303.zip ) with the following:
> - A VS2017 solution which provides a C++/MFC COM server app. The executable and tlb are also provided if they cannot be built. The executable must be run once to register the server.
> - A Python script which executes the provided COM methods and demonstrates two odd behaviors of win32com.
> - An Excel VBA example which executes the provided COM methods and demonstrates that they work successfully in other languages

This was the best I could do to help you at the time.

**Comment by mhammond** [comment] 2020-09-30 23:01
I had forgotten that, even though it's in the first comment :) Thanks, I'll try and make some time to dig into this.

**Comment by rleikis** [comment] 2020-10-01 01:13
You know, I just downloaded what I had originally attached and the python script was missing which tests the example COM server.  Perhaps it got stripped out?  I've included it again zipped and renamed to a text file.

[python_win32com_issue1303_comClient.zip](https://github.com/mhammond/pywin32/files/5308950/python_win32com_issue1303_comClient.zip)

[comClient.txt](https://github.com/mhammond/pywin32/files/5308954/comClient.txt)

**Closed** 2020-10-11 04:45 UTC

**Comment by mhammond** [comment] 2020-10-11 04:50
Thanks heaps for your sample - it helped alot. I'll get a new build out over the next couple of weeks.

**Comment by rleikis** [comment] 2020-10-12 15:36
Thanks Mark!
