### ISSUE TITLE
win32cred: TypeError in Attributes Dictionary

### ISSUE THREAD

**Issue by StefRe** [mhammond/pywin32#1710] opened 2021-06-03 13:16 UTC
```
import win32cred

attrs = [{'Keyword':'kw', 'Flags':0, 'Value':'val'}]
cred = {'UserName':'user', 'TargetName':'target', 'CredentialBlob':'pwd', 
        'Persist':win32cred.CRED_PERSIST_ENTERPRISE,'Type':win32cred.CRED_TYPE_GENERIC,
        'Attributes':attrs}

win32cred.CredWrite(cred)
```
`CredWrite` throws

> TypeError: a bytes-like object is required, not 'str'

This is related to the attributes dict (no error without the attributes). Changing the string values to `b'kw'` results in `TypeError: Objects of type 'bytes' can not be converted to Unicode.`

The [demo](https://github.com/mhammond/pywin32/blob/master/win32/Demos/win32cred_demo.py) throws the same error.

Python 3.8.2 / pywin32 301

**Comment by mhammond** [comment] 2021-09-05 06:08
This is a bit confusing :(

The problem is in PyWinObject_AsCREDENTIAL_ATTRIBUTE, which tries to use a unicode object with a buffer for the `value` param.  The docs https://docs.microsoft.com/en-us/windows/win32/api/wincred/ns-wincred-credential_attributew say declare `LPBYTE  Value` (meaning it's just bytes) but then the description says "Data associated with the attribute. By convention, if Value is a text string, then Value should not include the trailing zero character and should be in UNICODE.".

It turns out that with this patch, the demo works:

```
-    {'Keyword':'attr1', 'Flags':0, 'Value':'unicode data'},
-    {'Keyword':'attr2', 'Flags':0, 'Value':'character data'}
+    {'Keyword':'attr1', 'Flags':0, 'Value':b'unicode data'},
+    {'Keyword':'attr2', 'Flags':0, 'Value':b'character data'}
```

but clearly the demo is trying to show both bytes and unicode. So I'll try and get a fix for this before the next release, but in the meantime you can probably work around it by converting your unicode string to bytes and passing that.

**Closed** 2021-09-19 08:36 UTC
