### ISSUE TITLE
Problems with asciimatics and version 222

### ISSUE THREAD

**Issue by jabdoa2** [mhammond/pywin32#1152] opened 2018-01-26 15:55 UTC
With current versions of pywin32 we get problems in asciimatics:
```
  File "c:\projects\mpf\.eggs\asciimatics-1.9.0-py3.5.egg\asciimatics\screen.py", line 1545, in <module>
    import win32console
ImportError: DLL load failed: The specified module could not be found.
```

Version 219 seems to work fine. Cannot see from the changelog that win32console was removed.

**Comment by xoviat** [comment] 2018-01-26 16:54
Duplicate of gh-1151.

**Closed by xoviat** 2018-01-26 16:54 UTC
