### ISSUE TITLE
[Question] Does pywin32-221 have a whl version or could I install it in embedded python?

### ISSUE THREAD

**Issue by RidiculousDoge** [mhammond/pywin32#1960] opened 2022-11-01 06:24 UTC
I am embedding python on windows xp, which can only install python lower than 3.4.4.

I am using `pywin32==221`, cause it is the latest version for `cpython34` I could find.

However, only `exe` files are provided, and it requires native python installed.

Is there a way that `pywin32==221` can be installed by pip, or could I install it in my self-embedded python?

**Comment by mhammond** [comment] 2022-11-01 23:53
Your best bet is probably to rename the .exe installer to a .zip file, and manually install the various bits, then run `python pywin32_postinstall.py -install`. There's also the old `pypiwin32` package which I've no involvement in, but was intended to allow installation via .whl files before pywin32 itself adopted them, which may or may not help.

Let me know if you need more help, but I'll close this for now.

**Closed by mhammond** 2022-11-01 23:53 UTC

**Comment by RidiculousDoge** [comment] 2022-11-02 02:27
> Your best bet is probably to rename the .exe installer to a .zip file, and manually install the various bits, then run `python pywin32_postinstall.py -install`. There's also the old `pypiwin32` package which I've no involvement in, but was intended to allow installation via .whl files before pywin32 itself adopted them, which may or may not help.
> 
> Let me know if you need more help, but I'll close this for now.

Hi mhammond, thanks for your solution. 

I acctually managed to solve this problem by copying all file the `exe` file generates in my native python34 `lib/site-packages`
```
- adodapi
- isapi
- pythonwin
- pywin32_system32
- win32
- win32com
- win32comext
- pythoncom.py
- PyWin32.chm
- pywin32.pth
- pywin32.version.txt
- pywin32-221-py3.4.egg-info
```
I copied all the files listed above to my embedded python `Lib/site-packages` directory and add the following path to `%PythonPath%`:
```
Lib/site-packages/win32
Lib/site-packages/win32/lib
Lib/site-packages/pythonwin
```
I can `import win32api` now. But I am not sure if this works ok for all apis, cause I notice that when the `exe` file install `pywin32-221`, it also copied some `dll` files to `C:\\windows\\system32`
```
200 File Copy: C:\WINDOWS\system32\pythoncom34.dll
200 File Copy: C:\WINDOWS\system32\pywintypes34.dll
```

Is my way of doing this right? Or still I need to build from source? Cause when I run `py -3.4 pywin32_postinstall.py -install`, I encountered syntax error like:
```
$ py -3.4 pywin32_postinstall.py -install
  File "pywin32_postinstall.py", line 75
    except OSError, details:
                  ^
SyntaxError: invalid syntax 
```
seems like python 34 does not support this syntax.

**Comment by mhammond** [comment] 2022-11-02 04:53
> I encountered syntax error like:

Hrm - that's a little surprising to me - that should have been converted to python 3 syntax by the build process. Copying those DLLs will depend on what you are using pywin32 for - if you are just importing the modules and using them, then copying them next to python.exe and python34.dll (probably `sys.prefix`) is all you need. But if you are trying to run services or implement COM objects, you probably do want to copy them to system32.
