### ISSUE TITLE
ImportError:DLL load failed

### ISSUE THREAD

**Issue by Formartha** [mhammond/pywin32#1162] opened 2018-02-12 14:23 UTC
Hi,
We are using your package and for some reason it failed to work with raising the error listed bellow - care to assist?

ImportError while importing test module 'C:\automation_framework\new\playgr
Hint: make sure your test modules/packages have valid Python names.
Traceback:
playground\dina\test_ui1.py:1: in 
from core_framework.selenium_interface import SeleniumInterface
core_framework\selenium_interface.py:7: in 
from utilities.keyboard_util import KeyBoardUtil, k
utilities\keyboard_util.py:1: in 
from pykeyboard import PyKeyboard
C:\Python27\lib\site-packages\pykeyboard_init_.py:34: in 
from .windows import PyKeyboard, PyKeyboardEvent
C:\Python27\lib\site-packages\pykeyboard\windows.py:17: in 
import win32api
E ImportError: DLL load failed: The specified module could not be found.

**Comment by dhirschfeld** [comment] 2018-02-13 01:39
It's almost certainly not installed correctly. I'd recommend installing the anaconda python distribution and installing pywin32 via conda.

If you don't want to do that you can uninstall pywin32, delete all traces of it from site-packages and then re-install via pip however YMMV - conda was specifically designed to handle such packages with complex, non-python dependencies, pip was not.

**Comment by Formartha** [comment] 2018-02-13 05:55
Thanks for replying me.

The pywin32 came as out of the box installation of python. I didn't installed it.

P.S - I can see the win32api file listed under its location in site packages, it's just seems that it is corrupted.

Any way to trace back it's history? There is a chance that one of my recent packages holds some old pip-lock file with a defected dependency tree which messes up my installation.

**Comment by dhirschfeld** [comment] 2018-02-13 06:31
What Python distribution are you using? Python doesn't come installed by default on Windows and AFAIK `pywin32` isn't installed by the python.org installer.

> *Any way to trace back it's history?* 

Not AFAIK. `conda` on the other hand has the concept of *revisions* allowing you to rollback to a previously working environment.

My only advice (other than removing your existing Python and installing Anaconda) is to uninstall and reinstall `pywin32`. To help in case you go down that route the below are the folders installed by `pywin32` in my site-packages:

![image](https://user-images.githubusercontent.com/881019/36136179-e730fa90-10da-11e8-8ee6-32c68ef4d040.png)

**Comment by mhammond** [comment] 2018-02-13 06:41
If you installed via pypi, I suspect you need to run the post-install script as described in README.md. #1153 or similar will be used to fix that in the next build. Alternatively, just download one of the installer executables.

**Comment by xoviat** [comment] 2018-02-24 08:32
Duplicate of #1151.

**Closed by xoviat** 2018-02-24 08:32 UTC
