### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from versions: none)

### ISSUE THREAD

**Issue by pathakanuj24** [mhammond/pywin32#1834] opened 2022-02-19 12:18 UTC
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

* Steps to reproduce the problem.

* Version of Python and pywin32

**Comment by mhammond** [comment] 2022-02-20 04:25
Are you on Windows? What version of Python? The wheels are at https://pypi.org/project/pywin32/

**Comment by prithvi2k2** [comment] 2022-04-13 11:27
Same here, I'm facing the same issue on Docker
I raised an issue here: https://github.com/docker-library/python/issues/717
and also here https://github.com/ethereum/web3.py/issues/2423

I've also read about these issues on StackOverflow, seems like an inconsistency, please fix

**Comment by Avasam** [comment] 2024-09-11 21:50
Closing due to lack of answer from OP and assuming an attempt to install on a non-Windows system.
@pathakanuj24 Please let us know, with a minimal reproducer, if you are still getting this issue on a Windows machine.

---

> Same here, I'm facing the same issue on Docker [...]

https://github.com/ethereum/web3.py/issues/2423#issuecomment-1099168637
> This problem crops up on a regular basis. Why pywin32 should appear on a requirements list for a Linux installation is a mystery. As the "win32" indicates, pywin32 is a Windows-only package which wraps Windows system calls. It does not, can not, and will never work on a Linux system (other than within WINE). The requirements.txt file should add `; platform_system == "Windows"` to that line.

**Closed by Avasam** 2024-09-11 21:50 UTC
