### ISSUE TITLE
No LICENSE file available

### ISSUE THREAD

**Issue by philipaxer** [mhammond/pywin32#1681] opened 2021-03-25 08:26 UTC
Hi All,

I suggest to add a LICENSE file with the PSF license. At the moment the license is only available as meta data as part of setup.py
This is good practice. For example, tools such as pip-licenses allow to aggregate license information.

regards
Philip

**Comment by arihant2math** [comment] 2021-07-02 05:57
#1728 Resolves this.

**Comment by kennylajara** [comment] 2021-07-02 18:12
Hope you add the license

**Comment by arihant2math** [comment] 2021-07-02 19:52
@kennylajara That is up to mhammond to decide.

**Comment by Avasam** [comment] 2024-03-15 23:41
Closing as duplicate of https://github.com/mhammond/pywin32/issues/1127 and https://github.com/mhammond/pywin32/issues/1744 which have more complete discussions

**Closed by Avasam** 2024-03-15 23:41 UTC
