### ISSUE TITLE
import win32file not found

### ISSUE THREAD

**Issue by little-eyes** [mhammond/pywin32#1634] opened 2020-12-08 19:49 UTC
Note that issues in this repository are only for bugs or feature requests in the pywin32.

**If you need support or help using this package, please follow [these instructions](https://github.com/mhammond/pywin32/blob/master/README.md#support)** - support or help requests will be closed without comment.

For all bugs, please provide the following information.

* Expected behavior and actual behavior.

When I try to use `azure.identity` package to import `ClientSecretCredential`, it tries to import `win32file`, but python raise the following error.

```shell
ImportError: DLL load failed while importing win32file: The specified module could not be found.
```

I would expect the import to be successful.

* Steps to reproduce the problem.
  * using Python 3.8.3 or Python 3.8.5
  * install the latest `azure.identity==1.15.0` package
  * try  `from azure.identity import ClientSecretCredential`

* Version of Python and pywin32
  * Python 3.8.3 or 3.8.5
  * pywin32 227
  * Microsoft Windows [Version 10.0.19042.630]

**Comment by mhammond** [comment] 2020-12-08 21:22
Dupe of #1183, #1409, #1406 and a few others.

**Closed by mhammond** 2020-12-08 21:22 UTC

**Comment by dennisvang** [comment] 2021-11-19 16:42
This error can also arise if you've installed `pywin32` via `pip` inside a `conda` environment with python>=3.8.
Workaround in that case is to install `pywin32` via `conda` (from conda-forge, in my case), instead of `pip`.
More details [on SO](https://stackoverflow.com/a/70037907).

**Comment by Soppe** [comment] 2022-03-20 16:34
> This error can also arise if you've installed `pywin32` via `pip` inside a `conda` environment with python>=3.8. Workaround in that case is to install `pywin32` via `conda` (from conda-forge, in my case), instead of `pip`. More details [on SO](https://stackoverflow.com/a/70037907).

Had to scour for hours before finding this. In my case i also had to uninstall the pip-installed version of pywin32 that i had from god knows where. It was version 227. For whatever reason anaconda seemingly kept using this version instead of the conda version i had installed in my anaconda environment.

**Comment by vernondcole** [comment] 2022-03-21 12:13
At one time, the stock version of anaconda included pywin32 as part of its
default environment. My principal reason for avoiding conda was the fact
that they did not keep their copy (or fork?) of pywin32 up to date. It is
plausible that that is still going on. I have not checked. Will do that
when I have time.

**Comment by greekatos** [comment] 2022-12-02 09:08
> 

This is the right solution. I wondered two days why my exe wasn't working while my script did indeed worked. When I debugged the exe, this error popped: "ImportError: DLL load failed while importing win32api: The specified procedure could not be found. [20540] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!". The solution I found is located [here](https://github.com/brentvollebregt/auto-py-to-exe/issues/46#issuecomment-1112927236). Practically, I had to conda install pywin32 in anaconda console(admin mode) and then pip install all the other modules I needed.
