### ISSUE TITLE
win32file.FindFilesW crashes on Python 3.7.1

### ISSUE THREAD

**Issue by jan11011977** [mhammond/pywin32#1296] opened 2019-01-09 07:56 UTC
Calling win32file.FindFilesW with a filename that exists will cause an exception.

Steps to reproduce:
- Clean install of Python 3.7.1
- pip install pywin32

Run the following program:

    import win32file

    with open('file1.txt', 'w') as stream:
        stream.write('hello\n')
    finddata = win32file.FindFilesW('file1.txt')

**Comment by mhammond** [comment] 2019-01-09 12:05
What version of pywin32 is installed?

**Comment by jan11011977** [comment] 2019-01-09 12:11
pywin32==224

**Comment by mhammond** [comment] 2019-01-14 03:34
I can't reproduce this on 3.7.0 or 3.7.2. This sounds a lot like a problem that was fixed in build 224 - if is possible you have old pywin32 dlls floating around?

**Comment by jan11011977** [comment] 2019-01-14 09:52
Ah yes, sorry about that. I had some DLLs from an older version of PyWin32 in my path. Thank you for pointing me in the right direction!

**Closed** 2019-01-14 09:52 UTC
