### ISSUE TITLE
win32cred.CredRead segfaults on python 3.7

### ISSUE THREAD

**Issue by itziakos** [mhammond/pywin32#1232] opened 2018-08-14 21:16 UTC
Using the python 3.7 64bit and pywin32 223 from pypi I get a segfault when running the following example

```python
import win32cred
import faulthandler

faulthandler.enable()

username = u"john"
password = u"doefsajfsakfj"
comment = u"Created by MiniPyWin32Cred test suite"
target = "{0}@{1}".format(username, password)
credentials = {
    "Type": win32cred.CRED_TYPE_GENERIC,
    "TargetName": target,
    "UserName": username,
    "CredentialBlob": password,
    "Comment": comment,
    "Persist": win32cred.CRED_PERSIST_ENTERPRISE}
win32cred.CredWrite(credentials)
res = win32cred.CredRead(TargetName=target, Type=win32cred.CRED_TYPE_GENERIC)

print(res)
```
output with python 3.7
```python
>>python example.py 
Windows fatal exception: access violation

Current thread 0x00002514 (most recent call first):
  File "example.py", line 18 in <module>
```

output with python 3.5.1
```
>>python .\example.py
{'UserName': 'john', 'Comment': 'Created by MiniPyWin32Cred test suite', 'Type': 1, 'Attributes': (), 'Persist': 3, 'TargetAlias': None, 'LastWritten': pywintypes.datetime(2018, 8, 14, 21, 8, 42, 35000, tzinfo=TimeZoneInfo('GMT Standard Time', True)), 'CredentialBlob': b'd\x00o\x00e\x00f\x00s\x00a\x00j\x00f\x00s\x00a\x00k\x00f\x00j\x00', 'Flags': 0, 'TargetName': 'john@doefsajfsakfj'}
```

**Comment by itziakos** [comment] 2018-08-15 10:38
Note that the issue is similar to #670 which is supposed to have been fixed.

**Comment by matt-hoskins** [comment] 2018-08-16 09:29
From a quick squint at the code I think CredRead will lead to a call to PyWinObject_FromFILETIME from within PyWinObject_FromCREDENTIAL - could be the same root cause as what I report here:
https://github.com/mhammond/pywin32/issues/1233

**Comment by mhammond** [comment] 2018-09-28 06:54
I can't repro this with build 224, so I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.

**Closed by mhammond** 2018-09-28 06:54 UTC
