### ISSUE TITLE
No module named ‘win32api'

### ISSUE THREAD

**Issue by ucasiggcas** [mhammond/pywin32#1167] opened 2018-02-19 14:30 UTC
hello，have a question after pip install pywin32
there isn't   win32api, I don't know what's wrong.
have try many times,need help,  Thx

**Comment by xoviat** [comment] 2018-02-20 03:44
Duplicate gh-1151.

**Comment by xoviat** [comment] 2018-02-20 03:45
Duplicate of gh-1151.

**Comment by xoviat** [comment] 2018-02-20 03:46
Duplicate of gh-1151.

**Comment by xoviat** [comment] 2018-02-20 03:46
Duplicate of #1151.

**Comment by xoviat** [comment] 2018-02-20 03:47
Duplicate of #1151.

**Closed** 2018-02-20 03:47 UTC
