### ISSUE TITLE
Python 3.7: OverflowError in win32evtlog.ReadEventLog()

### ISSUE THREAD

**Issue by chrullrich** [mhammond/pywin32#1216] opened 2018-07-02 06:16 UTC
There is an internal error in win32evtlog.ReadEventLog() when using Python 3.7:

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from win32evtlog import *
>>> log = OpenEventLog(None, "Application")
>>> r = ReadEventLog(log, EVENTLOG_SEQUENTIAL_READ|EVENTLOG_BACKWARDS_READ, 0)
OverflowError: days=1732650298; must have magnitude <= 999999999

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function ReadEventLog> returned a result with an error set
```

Installed as a wheel from PyPI:

```
>type pywin32-223.dist-info\WHEEL
Wheel-Version: 1.0
Generator: bdist_wheel (0.30.0)
Root-Is-Purelib: false
Tag: cp37-cp37m-win_amd64
```

**Comment by chrullrich** [comment] 2018-08-04 15:59
I just managed, against all odds, to build enough of pywin32 for debug so I could try fixing it myself.

Data point: master works in debug and release. b223 does not build without the 7.1 SDK I'm not going to even try installing. The change from that SDK to the Windows 8.1 SDK (c2302d46ee2eb99c7e29e8325cc21ced07312b0c) is also by far the most likely commit to have accidentally fixed this.

**Comment by matt-hoskins** [comment] 2018-08-14 13:25
In trying to dig into an issue with crashes around calling something via COM which returns a datetime I found I was also getting OverFlow errors when I played around trying to construct PyTime objects.

I have python 3.7 with pywin32 installed via pip...
```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:06:47) [MSC v.1914 32 bit (Inte
l)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pythoncom
>>> import time
>>> pythoncom.MakeTime(time.time())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: days=1832760112; must have magnitude <= 999999999
>>> pythoncom.MakeTime(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: days=1832760112; must have magnitude <= 999999999
```
The number of days doesn't change regardless of what I pass into MakeTime for that given python session unless I exit and run python again.

If I import pywintypes and pass a value from time.time() into pywintypes.Time() then I get the same OverflowError (and indeed also get the same error if I pass in 0).

If I run the same code under python 2.7.14 on the same machine (also with pywin32 installed via pip) it runs fine and does what I expect.

Now the crash I mentioned earlier is calling a COM library which returns a datetime and via windbg I can see the crash is in new_date_ex on the line "self = (PyDateTime_Date *) (type->tp_alloc(type, 0));" with the call shown above being a call to PyWinObject_FromSYSTEMTIME. Again this is under python 3.7, but if I run the same short piece of test code on the same machine under python 2.7.14 it runs fine. So perhaps the same issue with time construction is also causing the crash I'ms eeing.

**Comment by chrullrich** [comment] 2018-08-14 22:57
What I don't get is where any quantity in days (let alone days enough for a few million years) does even show up in reading event log records. They have two timestamps, but both of them are actually the functional equivalent of `time_t`, not Windows' usual go-to time type `FILETIME`.

Also, the number from the error message (or rather, its constituent bytes) does not appear in the actual `EVENTLOGRECORD`, or at least I have not yet seen a case where it does. This looks to me like pywin32 is actually getting something fundamental wrong, like looking at the wrong buffer or corrupting a pointer resulting in a call to the wrong function.

**Comment by matt-hoskins** [comment] 2018-08-15 06:50
The Overflow exception in question is from the cpython datetime module and from check_delta_day_range which is only called (as far as I can see) from new_delta_ex. That really shouldn't be getting called for construction of datetime or PyTime objects! In terms of the value you're seeing on the overflow - in my tests it bore no relation to the value I was passing in to MakeTime, so I'm not surprised it's not a value you see in the event log.

I think you're right that there's something odd going on with function calls from pywin32 into cpython's datetime module. Looking at the crash I was seeing - PyWinObject_FromSYSTEMTIME does not actually have a call to new_date_ex in it anywhere, so that really shouldn't be below it in the call stack - I'd initially thought maybe there was just something missing from the call stack, but now I'm wondering if the call to PyDateTimeAPI->DateTime_FromDateAndTime is actually ending up calling new_date_ex but with the same arguments list (which means that a number of hours is being passed in as a PyTypeObject pointer, hence the exception).

Perhaps there's something wrong with the build environment used to build pywin32 for 3.7.0 under Windows as it seems to be how pywin32 calls _datetimemodule in cpython rather than anything related to Windows libraries. I'm using the 32 bit version and you're using the 64 bit version, so the issue is with both 3.7.0 builds. I'm going to install 3.6 and see if it behaves any differently.

**Comment by matt-hoskins** [comment] 2018-08-15 07:51
Seems to be fine with the build for python 3.6 - I felt it worth adding a new issue in the tracker with a more general title as it's actually something more fundamental with the date/time aspects of pywin32 under 3.7.0. I've not noticed any other issues with the scripts I've been running which use various aspects of win32com, so perhaps it's limited to how pywin32 interfaces with the datemodule.

**Comment by mhammond** [comment] 2018-09-28 06:57
I believe this will be fixed by https://github.com/mhammond/pywin32/releases/tag/b224 - please reopen if that's not the case.

**Closed by mhammond** 2018-09-28 06:57 UTC
