### ISSUE TITLE
MakePy utility doesn't work in Python 3.10

### ISSUE THREAD

**Issue by demberto** [mhammond/pywin32#1889] opened 2022-05-26 07:25 UTC
Trying to open the **COM Makepy utility** from **Pythonwin.exe** raises this exception:

```python
File "...\pythonwin\pywin\dialogs\list.py", line 68, in OnInitDialog
    self.FillList()
  File "...\pythonwin\pywin\dialogs\list.py", line 102, in FillList
    self.itemsControl.InsertColumn(index, itemDetails)
TypeError: 'float' object cannot be interpreted as an integer
win32ui.error: OnInitDialog() virtual handler (<bound method ListDialog.OnInitDialog of <pywin.dialogs.list.ListsDialog object at 0x000001A647D23160>>) raised an exception
```

This doesn't happen in 3.9 and below. Perhaps an explicit type cast is all that is needed

Environment:
- Python 3.10.0 64-bit
- PyWin32 303
- Windows 10 21H2 64-bit

**Comment by mhammond** [comment] 2022-05-26 07:29
This is a dupe of #1842, which was fixed in build 304.

**Closed by mhammond** 2022-05-26 07:29 UTC

**Comment by demberto** [comment] 2022-05-26 07:47
oh my bad, I didn't find it when I searched for it

**Comment by mhammond** [comment] 2022-05-26 08:09
Oops, the changelog omission is my fault, sorry about that!
